// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfgrkxmtphbgfilitioi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZ3JreG10cGhiZ2ZpbGl0aW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjMyMTAsImV4cCI6MjA3MDk5OTIxMH0.ofaQ7Mpu2nnY8dRkY5tt36WT5-pq5glOFIhOW7wtqY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});